#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'

# Custom prompt setup

function check_error() {
	if [ $? != 0 ]
	then
		echo ""
		echo "last command:$( history | tail -n 1 | sed 's/[0-9]\+//g' )"
	fi
}

PS1='[\u@\h \W] - $(check_error)\n$: '
PS2='=>>'

export PATH="$PATH:/$HOME/bin"
export EDITOR="nvim"

# echo fortune
echo -e "\n"
fortune -a
echo -e "\n"
