#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

export PATH="$PATH:/$HOME/bin"
export EDITOR="nvim"

# Fixing Java app window draw for JetBrains IDEs
export _JAVA_AWT_WM_NONREPARENTING=1
