#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

# Switch to the detected config on start
autorandr --change 
# Use autorandr profiles to set bspwm workspaces
auto_response=$( autorandr --current )

if [[ $auto_response == "work_monitors" ]]
then
	bspc monitor eDP1 -d  4 6 7 8
	bspc monitor HDMI1 -d 1 2 3 5 9 10
elif [[ $auto_response == "home_monitors" ]]
then
	bspc monitor HDMI-0 -d  2 3 5 9 10
	bspc monitor eDP-1 -d  1 4 6 7 8
else
	bspc monitor -d  1 2 3 4 5 6 7 8 9 10
fi

picom --backend glx &
feh --bg-max --random --recursive $HOME/Pictures/bg &
