#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

picom --backend glx &
feh --bg-fill --random --recursive $HOME/Pictures/bg &

# Set HDMI1 or HDMI0 to be the primary Display if detected
hdmi=$( xrandr --query | grep 'HDMI' )

if [[ $hdmi == *connected* ]]
then
	bspc monitor HDMI1 -d  2 3 5 10
	bspc monitor eDP1 -d  1 4 6 7 8 9
else
	bspc monitor eDP1 -d  1 2 3 4 5 6 7 8 9 10
fi
