#!/bin/bash
#Backs up all of the stuff I care about in gentoo
backup_array_config="${HOME}/bin/backup_array_config.txt"
git_repo_root="${HOME}/repos/local-linux-setups"
git_repo="${HOME}/repos/local-linux-setups/gentoo-backups/tas-work"

readarray -t backup_array < $backup_array_config

for dir in "${backup_array[@]}"
do
mkdir -p $git_repo/$( realpath $dir) && cp -r $dir/* $git_repo/$dir
done

cd $git_repo_root
git add .
git commit -m "$( date ) backup of gentoo"
git push
