#!/bin/bash

# Installs package list using pacman

PACKAGE_LIST="$1"

if [ -z $PACKAGE_LIST ]
then
	echo "Appears an empty package list argument was passed"
	echo "Expected list of packages."
	echo "exit 1"
	exit 1
fi

echo "If you haven't run a 'pacman -Syu' update, you should do that before running install_packlist"
echo
read -p "Move on without update? [Y/n]: " RESPONSE

if [ "$RESPONSE" == "y" ] || \
	[ "$RESPONSE" == "Y" ] || \
	[ "$RESPONSE" == "" ]
then
	echo "Moving forward"
elif [ "$RESPONSE" == "n" ]
then
	sudo pacman -Syu
fi

sudo pacman -S --needed $( cat $PACKAGE_LIST | sed "s/#.*//g" )
